### ISSUE TITLE
Title wrapped in quotes when org mode is on

### ISSUE THREAD

**Issue by anachronic** [kuanyui/hexo.el#19]
When I set up a new post with hexo with org mode activated, I get this layout:

```
#+TITLE: "Title input from minibuffer"
#+DATE: <2017-07-02 dom 01:54>
#+TAGS:
#+LAYOUT:
#+CATEGORIES:
```

Is this intended? I'd be happy to send a PR if it's not.

**Comment by kuanyui** [comment]
Yes it's intended, at least for Markdown.

Because in Markdown, the two quotes can prevent the errors occurred when
some special characters are included in.

I never tried any org -mode renderer for hexo, neither don't know how its
outputs actually looks. Org -mode supporting is contributed by its users,
what I've done was just giving some code reviewing. So if the quotes of
title really cause some problems, feel free to give pull request.

2017/07/02 午後1:57 "Nicolás Salas V." <notifications@github.com>:

When I set up a new post with hexo with org mode activated, I get this
layout:

#+TITLE: "Title input from minibuffer"
#+DATE: <2017-07-02 dom 01:54>
#+TAGS:
#+LAYOUT:
#+CATEGORIES:

Is this intended? I'd be happy to send a PR if it's not.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kuanyui/hexo.el/issues/19>, or mute the thread

**Comment by anachronic** [comment]
Cool, I'll give it a try and let you know shortly. Thanks.

**Comment by anachronic** [comment]
I have sent PR (#20). Please have a look when you have time.
